GET http://localhost:4004/odata/v4/catalog-pets/Pets

###
POST http://localhost:4004/odata/v4/catalog-pets/Pets
Content-Type: application/json

{
    "ID": 21,
     "type" : "Hamster",
     "name" : "Hamtaro",
     "gender" : "Male",
     "age" : "3 months"
    }
###
POST http://localhost:4004/odata/v4/catalog-pets/Adopters
Content-Type: application/json

{
    "CNI": "TT3124",
    "firstName": "name",
    "lastName": "lname",
    "telephone": "555-1234"
}